"""Initial migration

Revision ID: c565f6e0902f
Revises: 
Create Date: 2025-08-21 12:41:39.163626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c565f6e0902f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_label', sa.String(length=200), nullable=False),
    sa.Column('hindi_label', sa.String(length=200), nullable=True),
    sa.Column('sanskrit_label', sa.String(length=200), nullable=True),
    sa.Column('english_label', sa.String(length=200), nullable=True),
    sa.Column('mrsc', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_label')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('organization', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('otp_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sentence_id', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('wxtext', sa.Text(), nullable=True),
    sa.Column('englishtext', sa.Text(), nullable=True),
    sa.Column('segment_id', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sentence_type', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('annotator_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('annotation_status', sa.String(length=50), nullable=True),
    sa.Column('assign_lexical', sa.Boolean(), nullable=True),
    sa.Column('assign_construction', sa.Boolean(), nullable=True),
    sa.Column('assign_dependency', sa.Boolean(), nullable=True),
    sa.Column('assign_discourse', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], ),
    sa.ForeignKeyConstraint(['usr_id'], ['usr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('construction_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('cxn_index', sa.String(length=20), nullable=True),
    sa.Column('component_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['usr_id'], ['usr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('head_index', sa.String(length=20), nullable=True),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['usr_id'], ['usr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discourse_coref_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('head_index', sa.String(length=20), nullable=True),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['usr_id'], ['usr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lexical_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('semantic_category', sa.String(length=100), nullable=True),
    sa.Column('morpho_semantic', sa.String(length=100), nullable=True),
    sa.Column('speakers_view', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usr_id'], ['usr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence_type_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('sentence_type', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usr_id'], ['usr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence_type_info')
    op.drop_table('lexical_info')
    op.drop_table('discourse_coref_info')
    op.drop_table('dependency_info')
    op.drop_table('construction_info')
    op.drop_table('assignment')
    op.drop_table('usr')
    op.drop_table('segment')
    op.drop_table('sentence')
    op.drop_table('chapter')
    op.drop_table('user')
    op.drop_table('project')
    op.drop_table('concept')
    # ### end Alembic commands ###
